### ISSUE TITLE
Cannot run Demo

### ISSUE THREAD

**Issue by PomegranateApps** [hyperwallet/hyperwallet-ios-ui-sdk#292]
Is there a guide for getting the Demo to run? I'm not able to compile it using Xcode Version 12.3.

When I run `pod install` I get these errors.

```
[!] The target `ReceiptRepositoryTests` is declared multiple times.
The target `TransferMethodRepositoryTests` is declared multiple times.
The target `TransferMethodTests` is declared multiple times.
The target `TransferRepositoryTests` is declared multiple times.
```

I've tried editing the `Podfile` manually but I keep getting these errors in the different targets when compiling the `Demo` target.

```
.../TransferMethodConfigurationRepository.swift:19:8: No such module 'HyperwalletSDK'
.../ErrorView.swift:19:8: No such module 'HyperwalletSDK'
.../module.modulemap:9:12: Header 'Common-Swift.h' not found
```

**Comment by hamoody0706** [comment]
> Is there a guide for getting the Demo to run? I'm not able to compile it using Xcode Version 12.3.
> 
> When I run `pod install` I get these errors.
> 
> ```
> [!] The target `ReceiptRepositoryTests` is declared multiple times.
> The target `TransferMethodRepositoryTests` is declared multiple times.
> The target `TransferMethodTests` is declared multiple times.
> The target `TransferRepositoryTests` is declared multiple times.
> ```
> 
> I've tried editing the `Podfile` manually but I keep getting these errors in the different targets when compiling the `Demo` target.
> 
> ```
> .../TransferMethodConfigurationRepository.swift:19:8: No such module 'HyperwalletSDK'
> .../ErrorView.swift:19:8: No such module 'HyperwalletSDK'
> .../module.modulemap:9:12: Header 'Common-Swift.h' not found
> ```

**Comment by grmeyer-hw-dev** [comment]
Hi @PomegranateApps 

You can install the decencies using Carthage `carthage build --platform ios --use-xcframeworks`  then run the Demo
